require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'config/**/*'

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5
