services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: cursor_project_1_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP
    environment:
      SMTP_ADDRESS: 0.0.0.0
      SMTP_PORT: 1025
      HTTP_PORT: 1080

volumes:
  postgres_data:
  redis_data:
